### ISSUE TITLE
(클라) 화면을 반쪽을 쓸때 ToDo 화면을 옆에 사이드바처럼 넣을순 없나요?

### ISSUE THREAD

**Issue by I-AM-PROTO** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#102]
시간 있으면 ㅅㅅㅏ ㅂ ㄱ ㅏ ㄴ ㅡ ㅇ 인데
                        
네...
근데 있으면 진짜 좋긴하겠다

**Comment by Merseong** [comment]
ㅋㅋ 나중에 남으면 해보지 뭐
금요일에 달릴준비 하즈아
