### ISSUE TITLE
document의 onClick 속성에 jumpTo 사용하기

### ISSUE THREAD

**Issue by I-AM-PROTO** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#106]
mention 클릭으로 한번에 특정 페이지로 넘어가려면 documentPageLayout에서 getDerivedStateFromProps 부분 없애야함

**Comment by I-AM-PROTO** [comment]
이제 다른 문서나 페이지로 넘어가는건 context에서 jumpTo 함수 쓰면됨

**Comment by Merseong** [comment]
끝난거임??

**Comment by I-AM-PROTO** [comment]
되긴 했는데 문서 들어가기 전엔 documentContent 가 없어서 좀 걸림
mention으로 특정 페이지로 점프할라면 documentContent에서 pageId를 얻어와야되는데 mention을 눌렀을때 documentContent를 받아올라하면 좀 느려,,,
그래도 되기는 되니까 푸시해놓음

**Comment by Merseong** [comment]
미안 동후... 너가 만든거같은데 엎어버린듯
일단 되게는 바꿨으니 걱정 안해도 될거같긴한데
