### ISSUE TITLE
(클라) 문서 갱신시 그 문서 관련인들은 다 갱신

### ISSUE THREAD

**Issue by Merseong** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#116]
socket은 귀찮으니 단체로 broadcast 때리고 클라에서 걸러듣는걸로 함
문서 안으로 들어가면 이건 방으로 들어가는거라 방 안의 사람들만 서로 전파하면될듯

**Comment by I-AM-PROTO** [comment]
님님 저희 발표자료 우쨈 나 30분 뒤에 불침번인데
