### ISSUE TITLE
(클라) 테스트는 해보고 머지합시다...

### ISSUE THREAD

**Issue by Merseong** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#27]
![image](https://user-images.githubusercontent.com/44111580/95679398-8a570900-0c0d-11eb-8259-9a970e8562f0.png)
이게 맞니?
로그인버튼 누르자마자 터져버리는데

**Comment by I-AM-PROTO** [comment]
???????? 터질 수가 없는 버근데

제대로 볼라면 너가 어떻게 돌리는지 알아야되는데 알려줄 수 있음??

npm run dev 써보니까 안되든데 그걸로 돌린게 아닌가

**Comment by Merseong** [comment]
@I-AM-PROTO 서버로그론 안뜨는데 웹 켰을때 웹에서만 뜸. 위에 사진이 그게다야

**Comment by I-AM-PROTO** [comment]
아 미친 설마했는데 app.js 푸쉬가 안됐다 왜지;;;;; 미안합니다ㅠㅠㅠ

말 나온김에 이게 좀 문제인게 이 레포에서 돌리는 방법을 모르겠어서 내꺼에서 작업하고 복붙하는 식으로 하다보니까 터진거 같음 작업환경이 서로 안맞춰서 그런건데 그거부터 해결해야될듯...

**Comment by Merseong** [comment]
그거 서버폴더 클라폴더 둘다 들어가서 npm install 하고 서버폴더에서 npm run
오류생기면 npm install -g typescript
그래도 오류생기면 내가 밤에 봐줄게

**Comment by I-AM-PROTO** [comment]
다 해봤는데도 안되네,,, 서버는 돌아가는거 같은데 클라가 안뜸 왜지
일단 계속 해볼게

**Comment by I-AM-PROTO** [comment]
코드스페이스 너꺼에서 돌리면 터미널에서만 그럴듯하다가 페이지 들어가면 
![캡처](https://user-images.githubusercontent.com/38270326/95867421-1a2ebb80-0da4-11eb-871e-6829d68dda54.PNG)
이래뜨면서 안됨
으아아아아ㅏㅏㅏ

**Comment by I-AM-PROTO** [comment]
오 yarn 재설치하니까 된다
다시 커밋하겠습니다

**Comment by I-AM-PROTO** [comment]
...는 23시가 한계라 내일하겠습니다...

**Comment by Merseong** [comment]
1. 포트포워딩은 포트 3000번만 하면 됨
![캡처](https://user-images.githubusercontent.com/44111580/95873244-ae038600-0daa-11eb-93c0-4634e28a9942.PNG)
2. 서버 돌리던건 끄고 코드스페이스 꺼야됨... 만일 안그래서 다음에 켰을때 막 포트 사용중 오류가 뜬다면 코드스페이스 Suspend 후 다시 켜서 들어가면됨

일단 내가 방금 해봤는데 잘됨
```Bash
$ cd WEB_ROKTION_Yeonghon-s-Matdai/ROKTION-server/
$ npm run dev
```
