### ISSUE TITLE
(클라) 문서 구조 좀 뜯어고쳐야될거같은데요

### ISSUE THREAD

**Issue by Merseong** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#35]
1. 페이지별로 받아오는걸 따로 하고싶은데 딱히 그에 대한게 없음.
2. 페이지 받아오는중인지 여부도 하고싶은데 그런것도 없고
3. 몬가 콘텐츠 배열에 컴포넌트를 바로 박아버리는건 뭔가 좀...?

요것조것?

**Comment by I-AM-PROTO** [comment]
그럼 app.js 가 처음에 문서들 제목/id 목록만 받아오고 유저가 선택한 id를 서버에다가 요청해서 받아오게 만들겠음
그렇게되면 페이지 받아오는 중인지도 사이에 넣을 수 있을거 같은데 로딩화면 띄우려고 하는거야??
컴포넌트도 따로 관리할 수 있고 ㅇㅇㅇ

**Comment by Merseong** [comment]
@I-AM-PROTO 로딩화면 띄우는것도 있고, 요청이 여러번 보내져서 그럼
