### ISSUE TITLE
이번 머지 각오해랏

### ISSUE THREAD

**Issue by Merseong** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#36]
![image](https://user-images.githubusercontent.com/44111580/95872662-ff5f4580-0da9-11eb-9927-d7b0c0806d8e.png)

**Comment by Merseong** [comment]
@I-AM-PROTO 
제발 Pull해줘...
![Screenshot_20201017-205501_Chrome](https://user-images.githubusercontent.com/44111580/96336475-11e3c280-10bb-11eb-97c1-7c3d378d82a9.jpg)
https://jybaek.tistory.com/m/7750 참고

**Comment by I-AM-PROTO** [comment]
아 이게 풀 리퀘들 때문에 자꾸 뒤처져있다고 한거구나
이노무 깃린이를 우짤꼬,, ㅈㅅㅈㅅ
