### ISSUE TITLE
(클라) react-bootstrap 넣을까말까

### ISSUE THREAD

**Issue by I-AM-PROTO** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#4]
react-bootstrap에 sidebar가 없음
sidebar 있는거 보다가 semantic-ui 찾았는데 더 이쁘기까지함
https://react.semantic-ui.com/modules/sidebar/
요거 쓰는건 어떰

**Comment by Merseong** [comment]
좋다고생각함니다
ㄱㄱㄱ

**Comment by I-AM-PROTO** [comment]
ㅇㄱㅇㅇㅇ
