### ISSUE TITLE
태그 삭제할 때

### ISSUE THREAD

**Issue by I-AM-PROTO** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#40]
문서 보호가 우선(모든 문서에 해당 태그가 없어야 삭제 가능)
vs
태그 삭제가 우선(태그 없애면 문서 돌면서 해당 태그 삭제)

그리고 태그에도 삭제/수정 권한 넣어야할듯

**Comment by Merseong** [comment]
문서보호가 우선 ㄱㄱ
태그는 유저 개인이 붙이는거라 권한 딱히 없어도됨
유저 정보수정권한이랑 같이들어가
공용으로 정보를 보내는건 description이면 될듯
