### ISSUE TITLE
(클라) 사이드바에 태그별로 문서 보여주기

### ISSUE THREAD

**Issue by I-AM-PROTO** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#41]
문서에 태그 여러개 달려있으면 각 태그 하위에서 다 보여준다?

**Comment by Merseong** [comment]
이거 취소할까 생각중인데 어떰? 예정/진행/완료/문서 이 4개만 딱 나오고 나머진 최근 열어본 문서정도로 할까 생각중

**Comment by I-AM-PROTO** [comment]
ㅇㅇㅇ 좀 복잡해질거 같았는데 좋은 생각
태그는 예정/진행/완료/문서 + 중요 추가해서 5개하고 사이드바엔 최근 열어본 문서까지 추가해서 6개로 분류하는건 어떰
모든 문서에 주요 태그 4개 중에 하나는 넣도록 강제하는거도 괜찮을거 같고

**Comment by Merseong** [comment]
개굿개굿 개굿개굴
사랑해

**Comment by Merseong** [comment]
주요태그 4개는 필수적으로 넣어야됨 + 4개중 하나만 선택가능

**Comment by I-AM-PROTO** [comment]
만약 인수인계를 메인으로 간다 생각하면 사이드바에 보여주는 태그는 설정할 수 있도록 하거나 모든 태그를 보여줘야하지 않을까

**Comment by Merseong** [comment]
나도 보여주는 태그 설정하고 싶었는데 오래걸릴까봐 일단 스탑했음. 나중에 추가해도 될만한 기능인거같아.
그렇다고 모든태그 보여주면 너무 난잡해보일까봐 킵.
다른거 다 만들고 ㄱㄱ
