### ISSUE TITLE
(문서) 응기획다시해~~

### ISSUE THREAD

**Issue by Merseong** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#47]
가 아니고 사용 시나리오같은거 쓰자.
@I-AM-PROTO 너도 생각나는 시나리오 있으면 얘기점

**Comment by Merseong** [comment]
기준은 국방망 + 업무중(병사는 폰 못씀) 이라 생각하자.

1. 인수인계를 안전하게 오래오래 유지하고싶지만, 그걸 웹메일로 유지하긴 너무 귀찮다. + 수기나 프린트물로 작성하긴 지속적인 수정사항이 있다.
-> 문서-페이지 단위로 만들어 서버에 저장한다.

2. 한가지 큼지막한 업무(ex: 보안감사, 불용장비)에 대해 세부적인 지시사항들이 알고싶다.
-> 문서 하나에 업무 하나를 연결해 작성한다.
-> 페이지 내부에서 캘린더, 표, 체크박스 등으로 업무를 정리할 수 있다.
-> 공유해준 유저를 태깅해 업무를 분배할 수 있다. (@Merseong 이런식으로?)

3. 상관이 자기 컴퓨터 Sticky Notes에 써둔 업무 진행상황을 보고싶은데 직접 가서 보기 너무 힘들다.
-> 소유자가 문서를 공유하여 내 컴퓨터에서도 확인 가능하다.
-> 소유자가 수정권한을 부여해 업무 진행상황을 작성하면 동기화되어 다른 업무자도 확인이 가능하다.

4. 메모장으로 인수인계들을 유지하니 난잡한 곳에 저장되고 정리가 힘들다.
-> 태그로 문서를 정리 가능하고, 제목으로 문서를 필터링할 수 있다.

5. 어느 메모장에 원하는 내용이 있는지 찾기 힘들다.
-> 문서별, 페이지별 내용에 대한 검색을 할 수 있다.

6. 내가 계원인데 양식 백업하고싶다. OR 업무와 관련된 문서를 같이 놓고싶다.
-> 파일을 업로드 하고, 관리할 수 있다.

7. 맨날 터지는 휴가 정리 시트 싫다.
-> 안전하게 서버에 저장한다.
-> 짧은 주기로 저장되게 해서 최대한 손실이 적게 한다.

8. 내가 업무 지시자인데 계속 카톡이나 구두로 지시하는게 힘들고, 전달 오류가 생긴다.
-> 서-버 공-유
-> 원하는 사람에게만 공유하거나, 공유 문자열을 통해 필요한 사람이 알아서 들어오게 만든다.
-> 적어도 문서로 만들어두면 전달오류는 없지않을까?
-> 모르는 사항을 추가로 작성해두고 유저 언급(@)시 알림이 뜨게

9. 사실 맨날 전파가 안돼서 누구는 알고 누구는 모르고 해서 갈리는게 너무 많아서 만들고싶다.
-> 이런식으로 정보를 서로 공유하잔 얘기지... 아니면 다같이 화이트보드에 적고다니던가
-> 상황의 공유가 중점이라 생각해야될듯 Kanban 보드처럼

**Comment by Merseong** [comment]
쓰다보니 결국 ToDo는 메인이 아닌거같다.
기획 작성을 잘못한게 맞는듯

**Comment by I-AM-PROTO** [comment]
ROKTION의 주요 기능
- 원격저장소 문서 보관 및 백업
- 서버 공유를 통한 원격 문서 열람 및 다수 유저의 동시 수정
- 문서 정리가 가능한 태그 및 검색 시스템
- 다른 사용자 언급 및 업무분담

1. 전부터 생각했던건데 문서로 사용하려면 지금 쓰고있는 레이아웃보단 A4 크기에 화면 가운데정렬 된게 낫지 않을까? 구글독스 레이아웃처럼
    -> 달력 쓸때나 지도 옆에 붙일때는 가로 레이아웃이 좋긴한데 흠

2. 운전병 지원 요청할 때 굳이 배차계원 자리 찾아가서 메모 남겨야함
    -> 지원 요청 전용 문서를 만들어서 일괄적으로 처리할 수 있음

일단 여기까지밖에 생각이 안난다,, 생각나면 추가함
