### ISSUE TITLE
(서버-클라) VM 떴다!!!! 되는지 확인해야됨

### ISSUE THREAD

**Issue by Merseong** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#49]
접속법은 노션 참고,

**Comment by I-AM-PROTO** [comment]
ㅇㄱㅇㅇㅇ
보안감사 고생했다!!!

**Comment by I-AM-PROTO** [comment]
![image](https://user-images.githubusercontent.com/38270326/96595247-7060a900-1326-11eb-95a1-29ab30a6815a.png)

ssh에서 한 번 돌려봤는데 요래 뜨네 헤엘프 

그리고 VM 이거 동시접속 가능할거같음??

**Comment by Merseong** [comment]
VM 동접 안될거같은데,,,, 프로세스 겹치고 포트 겹쳐서 힘들듯
그리고 저거 오류는 고쳤긴함. 근데 포트포워딩 못해서 들어가진 못함..ㅎ.ㅎ

**Comment by Merseong** [comment]
현재 문제상황:
포트포워딩하고싶은데 방법을 모름
뭔가 그럴듯한걸 찾긴 했는데 권한이 막혀있음

**Comment by Merseong** [comment]
해 결 완 료
포트 80으로 쓰면 알아서 들어가지넹

**Comment by Merseong** [comment]
http://yeonghon-s-matdai.koreacentral.cloudapp.azure.com/
