### ISSUE TITLE
(클라) 화면에 흰 여백 안남게 풀로 땡겨야될듯

### ISSUE THREAD

**Issue by I-AM-PROTO** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#52]
흰 여백이 app영역 밖에 있는 여백 말하는거지? 그럼 app이 화면 꽉 채우도록 하자는거?

**Comment by Merseong** [comment]
ㅇㅇ 화면 크기 바꿔도 잘 적응되고 그렇게?

**Comment by I-AM-PROTO** [comment]
근데 옆으로 꽉 채우면 너무 길어지기도 하고 문서같은 경우엔 A4형태라든가 정해진 틀이 있어야 하는데 앱을 늘렸다 줄였다 하면 보기 힘들어지지 않을까
무엇보다 지금 만든 레이아웃도 겨우겨우 짜맞춘거라서 바꾸기 너무 어려워짐...
화면이 넓을 때 가운데정렬하도록 하는건 어떻게 생각하심

**Comment by Merseong** [comment]
음그런가
근데 지금처럼 좌측상단에 있고 나머지 흰여백 있는건 좀 아닌거같은데
고민이 필요할듯

**Comment by I-AM-PROTO** [comment]
일단 메인메뉴만 임시로 중간정렬 해봤음 어떤지 봐주세용

**Comment by Merseong** [comment]
몬가 2% 부족한 이느낌...
일단 대충 디자인안 좀더 생각해봤거든
![1안ㄴ](https://user-images.githubusercontent.com/44111580/96877311-72587280-14b4-11eb-8a41-ba7baff8c1d8.png)
![2안](https://user-images.githubusercontent.com/44111580/96877321-73899f80-14b4-11eb-9329-0936afcd628a.png)
어떤게 괜찮아보임? (아래꺼 사진의 아래부분은 비율참고용임)

**Comment by Merseong** [comment]
아님 좀더 알아봐야될듯.. 디자인은 젬병이라
web wireframe이라 검색하니 뭐 많이나오긴 하네

**Comment by I-AM-PROTO** [comment]
브런치 디자인 비슷하게 해보는거도 나쁘지 않은데
했으면 좋겠는건 첫번째 사진 > 두번째 사진 > 기존 디자인 인데
적용하기 쉬운건 역순이니 이것 참..
일단 급한대로 CKEditor 먼저 어떻게 해보고 결정해야할듯

**Comment by Merseong** [comment]
에디터 천천히 해도 되니 문서내용 페이지 디자인도 생각해봐

**Comment by I-AM-PROTO** [comment]
오른쪽 여백에 누가 어디서 자기 언급했는지 보여주는 언급리스트(#90) + google task처럼 쓸 수 있게 개인 메모장
이 두 개 semantic ui tab으로 넣어주면 좋지 않을까
![제목없음](https://user-images.githubusercontent.com/38270326/97155376-9ec40580-17b8-11eb-9067-216f2c870b19.png)
그림이 좀 하자긴 한데 암튼 이건 어떰

**Comment by Merseong** [comment]
ㅇㅎ 괜찮은듯
메모장은 별 기능없이 다른 문서에서도 공통으로 볼 수 있게 하면 좋을듯

**Comment by I-AM-PROTO** [comment]
ㅇㅇㅇ 맞아 그렇게 넣어주면 될듯
