### ISSUE TITLE
로그인하면 가끔 버그터짐

### ISSUE THREAD

**Issue by I-AM-PROTO** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#54]
문서 가져오는 부분에서 머가 있나보오

**Comment by I-AM-PROTO** [comment]
![스크린샷, 2020-10-21 19-45-35](https://user-images.githubusercontent.com/38270326/96709695-06074180-13d6-11eb-93a0-d670001ce968.png)

정상 작동하면 alert 0이랑 1인 문서 2개여야되는데 오른쪽 밑에 2짜리 나올때 버그터짐

**Comment by Merseong** [comment]
아마 고쳤으니 Pull 후 확인해줘
