### ISSUE TITLE
(클라) 문서데이터나 유저데이터는 따로 static으로 처리하면 안될까...?

### ISSUE THREAD

**Issue by Merseong** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#70]
https://ko.reactjs.org/docs/context.html#dynamic-context
Context 참고

**Comment by I-AM-PROTO** [comment]
오호
문서랑 유저데이터를 아예 다른 곳에서 컨텍스트로 처리한 다음에 app 하위 아무데서나 쓸 수 있게 하자는거지
좋은데??? 나 색상고르는거 마무리만 하고 함 해볼겡

**Comment by I-AM-PROTO** [comment]
context 해볼라 하는데 어디까지 포함시켜야 할질 모르겠네
일단 MainMenuLayout이랑 DocumentPage에 들어가는 애들 대부분 꽤 깊이 들어가길래 전부 컨텍스트에 넣었는데 좀 과한느낌이 드네
```javascript
const userContext = React.createContext({
    loginStatus: 0,
    userInfo: {},
    selectedDocumentId: -1,
    documents: [],
    tags: [],
    handleLogout: ()=>{},
    toMainMenu:()=>{},
    createNewMention: ()=>{},
    addPageAfter: ()=>{},
    removePage: ()=>{},
    addNewTag: ()=>{},
    deleteTag: ()=>{},
    changeDocumentSettings: ()=>{},
    toggleTagInDocument: ()=>{},
    createNewDocument: ()=>{},
    deleteDocument: ()=>{},
    shareDocument: ()=>{},
});
```
MainMenuLayout이랑 DocumentPage 둘이 같은 컨텍스트 안에 넣을 생각임

**Comment by I-AM-PROTO** [comment]
오 미친 documentPage에서 props 아예 안불러도 되는거였어 개깔끔하지네 ㄷㄷㄷㄷ

**Comment by Merseong** [comment]
근데 안터지게 다 바꿀수 있겠음?
고생이 많다...

**Comment by I-AM-PROTO** [comment]
그래서 지금 불안함 ㅋㅋㅋㅋㅋ... 일단 해보고 안되면 리셋해야지 머

**Comment by I-AM-PROTO** [comment]
적용 생각보다 할만하긴 한데 getDerivedFromState 에서 부르는 prop은 사실상 컨텍스트로 못넣음 이따 연등하고 마저 해야겠따

**Comment by I-AM-PROTO** [comment]
다 적용해서 잘 돌아가는거 같긴한데 머지하기 전에 한 번 백업해두는게 나으려나

**Comment by I-AM-PROTO** [comment]
터질거 같진 않으니까 내 코드스페이스에 로컬하게 백업해놓음

**Comment by Merseong** [comment]
ㅇㄱㅇ
고생많았으 동후쿤
