### ISSUE TITLE
(클라) 야!!!@!@!@>!@>!@!>@!@>김도무!ㅏ!@ㅒ#ㅏ!ㅒ@#ㅏ

### ISSUE THREAD

**Issue by Merseong** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#74]
@I-AM-PROTO 
![image](https://user-images.githubusercontent.com/44111580/97069847-fd00b500-160d-11eb-945f-3953469b5885.png)
이게맞아?

**Comment by Merseong** [comment]
클라에서만 쓰는거기 때무네 ROKTION-client 안에서 해주시기 바랍니다...
pull받고는 npm i 한번 돌려주면 되는거구
@I-AM-PROTO @I-AM-PROTO @I-AM-PROTO @I-AM-PROTO @I-AM-PROTO

**Comment by I-AM-PROTO** [comment]
으아아ㅏㅏ악 미안해ㅠㅠㅠㅠㅠㅜㅠㅠ
client 안에서만 했다가 안되서 이것저것 만져보다가 그만,,,,
uninstall하면 해결될줄 알았는데 넘모 멍청했던것..

그럼 저렇게 잘못 설치하면 새로 pull 받아서 덮어씌워야 되는거야?????

**Comment by Merseong** [comment]
ㄴㄴ 최상위에 node_modules 지우고 어쩌구lock.json 지우고
ROKTION-client 폴더 들어가서 다시 npm install --save 어쩌구저쩌구 다시 하면됨

만일 오류나면 ROKTION-client/node_modules, 어쩌구lock.json 삭제후
다시 npm install 하면됨

팁) install할때 --save하면 package.json에 기록돼서 npm install 했을때 알아서 깔아줌

**Comment by I-AM-PROTO** [comment]
아 아예 갈아엎어야 되는거구나..
조심해야겠구만

**Comment by Merseong** [comment]
그리고 수정후 pull request 보낼때 내용에 close #03 이런식으로 쓰면 이슈 자동으로 닫힘 신기방기
