### ISSUE TITLE
(클라) 왜 또 페이지 2개밖에 안보이니

### ISSUE THREAD

**Issue by Merseong** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#75]
![image](https://user-images.githubusercontent.com/44111580/97070051-173b9280-1610-11eb-95ed-7e0e546d7117.png)
팩트) 이거 DB에선 페이지 4개다

**Comment by I-AM-PROTO** [comment]
?? 나 오늘은 메인메뉴만 만지고 있었는데???

**Comment by Merseong** [comment]
ㄱㄷ DB문제일수 있어서 내가 일단 보는중

**Comment by I-AM-PROTO** [comment]
오우 쮔 태그랑 문서 날라갔는데??

**Comment by Merseong** [comment]
아니먼데
