### ISSUE TITLE
(클라) 사이드바 컬러 변경?

### ISSUE THREAD

**Issue by Merseong** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#81]
#52565a
![image](https://user-images.githubusercontent.com/44111580/97083446-12e09b00-164b-11eb-96e4-fb2de4874323.png)
#353535
![image](https://user-images.githubusercontent.com/44111580/97083461-46232a00-164b-11eb-9fa3-359f8309628e.png)
#737373
![image](https://user-images.githubusercontent.com/44111580/97083481-66eb7f80-164b-11eb-9000-cd2f752a3bf4.png)

**Comment by I-AM-PROTO** [comment]
첫번째꺼가 제일 괜찮다 그중에선

**Comment by I-AM-PROTO** [comment]
ㅇㅇㅇ 다른 색 골라봐도 그게 더 나은거같음!
