### ISSUE TITLE
(클라) 회원가입 만들기

### ISSUE THREAD

**Issue by Merseong** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#82]
페이지 말고 그냥 모달로 가능?
[이런 느낌?](https://www.google.com/search?q=sign+up+modal&tbm=isch&ved=2ahUKEwjB-qfzsc3sAhULXpQKHWTxBhEQ2-cCegQIABAA&oq=sign+up+modal&gs_lcp=CgNpbWcQAzIECAAQEzoICAAQBxAeEBM6CggAEAcQBRAeEBNQ4mFYmG5g7W9oAHAAeACAAbcBiAGFBZIBAzAuNZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=eTOUX4HaA4u80QTk4puIAQ&bih=959&biw=958&rlz=1C1CHZN_koKR924#imgrc=iWnYZImbxWwc-M)

**Comment by I-AM-PROTO** [comment]
받아야 될 정보가

아이디
비밀번호
비밀번호 확인
이름
소속(그냥 input 던져주고 쓰라 하면 되나)
계급
군번
생년월일? (군번 있는데 필요한가)
이메일? (선택)
전화번호? (선택?)
군 일반전화(행정반)

osam이랑 naver 참고해서 뽑아봤는데 더 필요한거 있나

**Comment by Merseong** [comment]
일단 급한대로

군번 string (== 아이디)
비밀번호
비밀번호 확인
계급 string
이름 string
소속 string

정도?

**Comment by I-AM-PROTO** [comment]
군번 아이디로 하는거 괜찮네
컴퓨터 터져가지고 지금은 어렵고 내일 회원가입 완료 화면 바꾸면서 같이 해야겠다
