### ISSUE TITLE
데이터 처리관련

### ISSUE THREAD

**Issue by I-AM-PROTO** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#90]
오늘 고민할 시간이 굉장히 많았다

- 문서 데이터
1. 서버에 모든 문서의 리스트를 저장한다
2. 각 유저 오브젝트에 유저가 볼 수 있는 문서의 id 리스트인 docList를 저장한다
3. 유저가 로그인 할 때 서버의 문서리스트를 docList로 필터링해서 로컬에 보내준다

- 언급하기
1. 각 유저 오브젝트에 mentionList를 저장한다
2. 한 유저가 어떤 문서의 페이지를 다른 유저의 아이디(군번)을 입력해서 언급을 하면 언급된 유저의 mentionList에 추가한다
3. 오른쪽 여백에 언급된 유저에게 누가 어느 문서의 어느 페이지로 언급했는지 띄우고, 그 페이지로 연결되도록 한다  (#52)
4. alert는 document의 속성이 아니라 유저 docList의 속성이 되어야 할 듯

굿?

**Comment by Merseong** [comment]
일단 문서리스트 관련은 문서 전부의 목록을 로컬로 가져온다음 본다는거 자체가 좀 위험하다고 생각
서버에서 필터거르면 모를까

언급은 괜찮은듯, 공유설정에 없는 사람이면 안뜨게 하면되고

**Comment by I-AM-PROTO** [comment]
그럼...
1. 유저 docList를 서버로 보낸다
2. 서버에서 필터링한 문서 id 리스트를 반환한다
3. 유저가 선택한 문서의 내용을 서버에서 받아온다
요거면 좀 나으려나

**Comment by Merseong** [comment]
아 미안 내가 이해를 잘못했었네
너가 말한대로 이미 DB가 구성되어있음
모든 DocInfo들이 한 콜렉션에 들어가있고, 유저한테는 DocInfo의 id 리스트가 있음

**Comment by I-AM-PROTO** [comment]
역시 24수 앞을 생각하고 움직이는 갓머성 그는 대체 누구인가!!
ㅇㅎㅇㅎ 그럼 docList에 authority랑 alert도 되면 넣어보는건 어때
authority: 문서를 만든 유저는 admin으로, 다른 유저에게 공유할 때 read, write, admin 중에 설정해서 공유해서 저장해놓고 read면 읽기모드로만 로드해주면 되니까 쓸만할듯
alert: 각 문서에서 자기가 얼마나 언급되었는지니까 유저마다 따로 관리해야할거같아

mention은 되는대로 만들어볼겡

**Comment by Merseong** [comment]
authority는 이미 shareOption이라는 이름으로 있긴하고
alert는 만들게
ㄱㄱㄱ
