### ISSUE TITLE
ROKTION 발표자료 만화 넣어보는건 어떨까

### ISSUE THREAD

**Issue by I-AM-PROTO** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#91]
정보공유체계가 없어서 불편하다는걸 좀 인지를 시켜줘야 되는데
영상을 찍기엔 여건이 안되고 글로만 쓰자니 와닿지가 않고 해서 만화로 좀 그려봤는데
사진을 못찍음ㅋㅋㅋㅋㅋㅋㅋㅋ

대충 구도는 이럼
세로로 두 줄짜리 만환데 같은 상황을 두고 왼쪽은 ROKTION이 없는경우 오른쪽은 ROKTION을 쓴 경우

기본상황: 신병이 전입와서 계원이 되었는데 인수인계 해줄 선임이 말출나감. 복귀해서 알려준다 해놓고 코로나 터져서 고대로 자가전역함(우리 부대서 실제로 일어남).

상황 1: 선임이 인수인계 문서를 남기고 가서 다른 선임들이 찾아준다 함
ROKTION X: 헤멤 -> 이 파일은 왜 여기 있느냐고 정리하라 하지 않았느냐고 싸움
ROKTION O: 일단 ROKTION 가입하라 하고 문서 공유해줬으니 일어보라고 함 -> 평온하게 문서 많아져서 섞이니까 태그 붙여서 정리하라고 알려줌

상황 2: "야야 일단 간부님이 시킨거부터 해라"
ROKTION X: "시키신거 다 했습니다" "너네 왜 메모장이랑 바탕화면에 써놓은건 안했냐" "아,,"
ROKTON O: "ROKTION에서 저희 앞으로 지시 언급해놓으신거 다 해놨습니다. 필요한 품목은 옆에 적어놨으니 보시면 될 것 같습니다" "오 훌륭하다!"

뭐 이정도??? 뭔가 굉장히 호들갑 떠는거 같다 쓰고 나니까

**Comment by Merseong** [comment]
ㅋㅋㅋㅋㅋㅋㅋ 커엽당
그거 간부 폰으로 찍어다가 보내달라그래 ㅋㅋ

**Comment by I-AM-PROTO** [comment]
ㅋㅋㅋㅋㅋㅋㅋ 그림 개못그려서 쪽팔림
등장인물은 신병 한명뿐임
![image](https://user-images.githubusercontent.com/38270326/97164437-768ed380-17c5-11eb-8c2c-455537a2099d.png)
이래 생겨가지고 표정은 :) 랑 :( 두개밖에 없고 위치랑 자세도 똑같이 유지하면서 말풍선만 바꿀 생각이어서 만들기는 편한데 귀엽게 만들수 있을듯

**Comment by I-AM-PROTO** [comment]
이제 남은것들은 금방 끝낼 수 있으니까 이따 연등때하고 지금은 발표자료 좀 만들어볼게 급한거 있으면 말해줭

**Comment by I-AM-PROTO** [comment]
다 그렸당
![슬라이드0001](https://user-images.githubusercontent.com/38270326/97699825-275ee080-1aee-11eb-833a-5dc8b1aaca35.jpg)
![슬라이드0002](https://user-images.githubusercontent.com/38270326/97699828-27f77700-1aee-11eb-9cb5-64346e6c3bc2.jpg)
![슬라이드0003](https://user-images.githubusercontent.com/38270326/97699830-28900d80-1aee-11eb-800c-edca3d2a21c0.jpg)
![슬라이드0004](https://user-images.githubusercontent.com/38270326/97699834-28900d80-1aee-11eb-8e0b-3272ee43947e.jpg)
![슬라이드0005](https://user-images.githubusercontent.com/38270326/97699835-2928a400-1aee-11eb-8e8c-b7757398e3b2.jpg)
![슬라이드0006](https://user-images.githubusercontent.com/38270326/97699836-29c13a80-1aee-11eb-844b-ea1a7943cca6.jpg)
![슬라이드0007](https://user-images.githubusercontent.com/38270326/97699840-29c13a80-1aee-11eb-81c1-e3a0b44efbc4.jpg)
![슬라이드0008](https://user-images.githubusercontent.com/38270326/97699844-2a59d100-1aee-11eb-8acb-19bb97c6258b.jpg)
![슬라이드0009](https://user-images.githubusercontent.com/38270326/97699846-2a59d100-1aee-11eb-8fa7-e737ce4e6984.jpg)

**Comment by I-AM-PROTO** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by Merseong** [comment]
왤케귀엽누 ㅋㅋㅋ
