### ISSUE TITLE
(서버) 쓰기싫었지만... socket을 써야될수도

### ISSUE THREAD

**Issue by Merseong** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#94]
1. 실시간 상호갱신에 써야됨
2. alert 오면 다시 갱신하라고 신호보낼때 써야됨

소켓없이 서버에서 클라로 신호 보내는법을 모르겠다

**Comment by Merseong** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

있긴 하네
근데 걍 소켓쓸래...

**Comment by I-AM-PROTO** [comment]
ㅎㅇㅌ...
